[package]
name = "kernel"
version = "0.1.0"
authors = ["MD Gaziur Rahman Noor <mdgaziurrahmannoor@gmail.com>"]
edition = "2021"

[lib]
path = "kernel.rs"
crate-type = ["staticlib"]

[dependencies]
utils = { path = "../utils" }
multiboot2 = "0.14.0"
bitflags = "1.3.2"
linked_list_allocator = "0.10.2"
spin = "0.9.4"
bit_field = "0.10.1"
pic8259 = "0.10.1"
pc-keyboard = "0.5.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
font8x8 = { version = "0.3.1", default-features = false, features = ["unicode"] }
once = { version = "0.3.4" }
uart_16550 = "0.2.18"
volatile = "0.4.5"
uefi = "0.16.0"

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]

[dependencies.crossbeam-queue]
version = "0.3.6"
default-features = false
features = ["alloc"]

[dependencies.conquer-once]
version = "0.3.2"
default-features = false

[target.'cfg(target_arch="x86_64")'.dependencies]
x86_64 = "0.14.10"
